/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesWardrobesRouteImport } from './routes/services/wardrobes'
import { Route as ServicesLivingSpacesRouteImport } from './routes/services/living-spaces'
import { Route as ServicesKitchensRouteImport } from './routes/services/kitchens'
import { Route as ServicesInteriorsRouteImport } from './routes/services/interiors'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as AdminWhyRouteImport } from './routes/admin/why'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminJournalRouteImport } from './routes/admin/journal'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminAboutRouteImport } from './routes/admin/about'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesWardrobesRoute = ServicesWardrobesRouteImport.update({
  id: '/wardrobes',
  path: '/wardrobes',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLivingSpacesRoute = ServicesLivingSpacesRouteImport.update({
  id: '/living-spaces',
  path: '/living-spaces',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesKitchensRoute = ServicesKitchensRouteImport.update({
  id: '/kitchens',
  path: '/kitchens',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInteriorsRoute = ServicesInteriorsRouteImport.update({
  id: '/interiors',
  path: '/interiors',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const AdminWhyRoute = AdminWhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJournalRoute = AdminJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/journal': typeof JournalRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/why': typeof AdminWhyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/interiors': typeof ServicesInteriorsRoute
  '/services/kitchens': typeof ServicesKitchensRoute
  '/services/living-spaces': typeof ServicesLivingSpacesRoute
  '/services/wardrobes': typeof ServicesWardrobesRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/journal': typeof JournalRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/why': typeof AdminWhyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/interiors': typeof ServicesInteriorsRoute
  '/services/kitchens': typeof ServicesKitchensRoute
  '/services/living-spaces': typeof ServicesLivingSpacesRoute
  '/services/wardrobes': typeof ServicesWardrobesRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/journal': typeof JournalRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/why': typeof AdminWhyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/interiors': typeof ServicesInteriorsRoute
  '/services/kitchens': typeof ServicesKitchensRoute
  '/services/living-spaces': typeof ServicesLivingSpacesRoute
  '/services/wardrobes': typeof ServicesWardrobesRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/gallery'
    | '/journal'
    | '/services'
    | '/admin/about'
    | '/admin/config'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/health'
    | '/admin/journal'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin/why'
    | '/services/$slug'
    | '/services/interiors'
    | '/services/kitchens'
    | '/services/living-spaces'
    | '/services/wardrobes'
    | '/admin/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gallery'
    | '/journal'
    | '/admin/about'
    | '/admin/config'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/health'
    | '/admin/journal'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin/why'
    | '/services/$slug'
    | '/services/interiors'
    | '/services/kitchens'
    | '/services/living-spaces'
    | '/services/wardrobes'
    | '/admin'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/gallery'
    | '/journal'
    | '/services'
    | '/admin/about'
    | '/admin/config'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/health'
    | '/admin/journal'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin/why'
    | '/services/$slug'
    | '/services/interiors'
    | '/services/kitchens'
    | '/services/living-spaces'
    | '/services/wardrobes'
    | '/admin/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  JournalRoute: typeof JournalRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/wardrobes': {
      id: '/services/wardrobes'
      path: '/wardrobes'
      fullPath: '/services/wardrobes'
      preLoaderRoute: typeof ServicesWardrobesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/living-spaces': {
      id: '/services/living-spaces'
      path: '/living-spaces'
      fullPath: '/services/living-spaces'
      preLoaderRoute: typeof ServicesLivingSpacesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/kitchens': {
      id: '/services/kitchens'
      path: '/kitchens'
      fullPath: '/services/kitchens'
      preLoaderRoute: typeof ServicesKitchensRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/interiors': {
      id: '/services/interiors'
      path: '/interiors'
      fullPath: '/services/interiors'
      preLoaderRoute: typeof ServicesInteriorsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/admin/why': {
      id: '/admin/why'
      path: '/why'
      fullPath: '/admin/why'
      preLoaderRoute: typeof AdminWhyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/journal': {
      id: '/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AdminJournalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminJournalRoute: typeof AdminJournalRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminWhyRoute: typeof AdminWhyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminJournalRoute: AdminJournalRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminWhyRoute: AdminWhyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesInteriorsRoute: typeof ServicesInteriorsRoute
  ServicesKitchensRoute: typeof ServicesKitchensRoute
  ServicesLivingSpacesRoute: typeof ServicesLivingSpacesRoute
  ServicesWardrobesRoute: typeof ServicesWardrobesRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesInteriorsRoute: ServicesInteriorsRoute,
  ServicesKitchensRoute: ServicesKitchensRoute,
  ServicesLivingSpacesRoute: ServicesLivingSpacesRoute,
  ServicesWardrobesRoute: ServicesWardrobesRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  GalleryRoute: GalleryRoute,
  JournalRoute: JournalRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
